from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(story)
admin .site.register(story2)
admin .site.register(story3)
admin .site.register(story4)
admin .site.register(story5)
admin .site.register(story6)
admin .site.register(story7)
admin.site.register(story8)
admin.site.register(story9)
admin.site.register(story14)
admin.site.register(story15)
admin.site.register(story16)
admin.site.register(story17)
admin.site.register(story18)
admin.site.register(story19)
admin.site.register(story20)
admin.site.register(story22)
admin.site.register(kantak)
admin.site.register(kantakt2)
admin.site.register(march)
admin.site.register(camment)
admin.site.register(izoh)
admin.site.register(post)
admin.site.register(post2)
admin.site.register(xarid)
admin.site.register(xarid3)
admin.site.register(loyiha)
admin.site.register(page)
admin.site.register(jamoa)
admin.site.register(jamoa2)
admin.site.register(dehqon)