# Generated by Django 6.0.6 on 2026-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_story2'),
    ]

    operations = [
        migrations.CreateModel(
            name='story3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
