# Generated by Django 6.0.6 on 2026-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_story7'),
    ]

    operations = [
        migrations.CreateModel(
            name='story8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
