# Generated by Django 6.0.6 on 2026-09-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_story10_story11_story12_story13'),
    ]

    operations = [
        migrations.CreateModel(
            name='story14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narx', models.FloatField()),
                ('image', models.ImageField(upload_to='media/')),
                ('xarid', models.CharField(max_length=100)),
            ],
        ),
    ]
