# Generated by Django 6.0.6 on 2026-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_story14'),
    ]

    operations = [
        migrations.CreateModel(
            name='story15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('nomi2', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='story10',
        ),
        migrations.DeleteModel(
            name='story11',
        ),
        migrations.DeleteModel(
            name='story12',
        ),
        migrations.DeleteModel(
            name='story13',
        ),
    ]
