# Generated by Django 6.0.6 on 2026-09-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_story15_delete_story10_delete_story11_delete_story12_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='story16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('nomi2', models.CharField(max_length=100)),
            ],
        ),
    ]
