# Generated by Django 6.0.6 on 2026-09-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_story16'),
    ]

    operations = [
        migrations.AddField(
            model_name='story16',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
