# Generated by Django 6.0.6 on 2026-09-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_story19_story20_story21_story22'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('nomi2', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
