# Generated by Django 6.0.6 on 2026-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_kantak'),
    ]

    operations = [
        migrations.CreateModel(
            name='kantakt2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=100)),
                ('Usrename', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.FloatField()),
                ('massage', models.CharField(max_length=100)),
            ],
        ),
    ]
