# Generated by Django 6.0.6 on 2026-09-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_kantakt2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kantakt2',
            old_name='Usrename',
            new_name='Username',
        ),
    ]
