# Generated by Django 6.0.6 on 2026-09-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_usrename_kantakt2_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kantakt2',
            name='Message',
        ),
    ]
