# Generated by Django 6.0.6 on 2026-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_kantakt2_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='march',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('nomi2', models.CharField(max_length=100)),
                ('nomi3', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
