# Generated by Django 6.0.6 on 2026-09-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_march'),
    ]

    operations = [
        migrations.CreateModel(
            name='camment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('sana', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('nomi2', models.CharField(max_length=100)),
            ],
        ),
    ]
