# Generated by Django 6.0.6 on 2026-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_camment'),
    ]

    operations = [
        migrations.AddField(
            model_name='camment',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
