# Generated by Django 6.0.6 on 2026-09-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_camment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('mavzu', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
