# Generated by Django 6.0.6 on 2026-09-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
    ]
