# Generated by Django 6.0.6 on 2026-09-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_post2'),
    ]

    operations = [
        migrations.CreateModel(
            name='xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narx', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('nomi2', models.CharField(max_length=100)),
                ('nomi3', models.CharField(max_length=100)),
                ('nomi4', models.CharField(max_length=100)),
            ],
        ),
    ]
