# Generated by Django 6.0.6 on 2026-09-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_xarid'),
    ]

    operations = [
        migrations.CreateModel(
            name='xarid2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('nomi2', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
