# Generated by Django 6.0.6 on 2026-09-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_xarid3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xarid3',
        ),
        migrations.RemoveField(
            model_name='xarid',
            name='narx',
        ),
        migrations.RemoveField(
            model_name='xarid',
            name='nomi3',
        ),
        migrations.RemoveField(
            model_name='xarid',
            name='nomi4',
        ),
        migrations.RemoveField(
            model_name='xarid',
            name='title',
        ),
        migrations.RemoveField(
            model_name='xarid2',
            name='nomi',
        ),
        migrations.RemoveField(
            model_name='xarid2',
            name='nomi2',
        ),
        migrations.AddField(
            model_name='post2',
            name='narx',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post2',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xarid',
            name='text',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
