# Generated by Django 6.0.6 on 2026-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_delete_xarid3_remove_xarid_narx_remove_xarid_nomi3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xarid',
            name='text',
        ),
        migrations.RemoveField(
            model_name='xarid2',
            name='text',
        ),
        migrations.AddField(
            model_name='xarid',
            name='narx',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xarid',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xarid2',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
