# Generated by Django 6.0.6 on 2026-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_xarid_text_remove_xarid2_text_xarid_narx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='xarid3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='xarid2',
            old_name='title',
            new_name='nomi',
        ),
        migrations.AddField(
            model_name='xarid2',
            name='nomi2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xarid2',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
