# Generated by Django 6.0.6 on 2026-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_xarid3_rename_title_xarid2_nomi_xarid2_nomi2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
