# Generated by Django 6.0.6 on 2026-09-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_loyiha'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('nomi2', models.CharField(max_length=100)),
                ('nomi3', models.CharField(max_length=100)),
            ],
        ),
    ]
