# Generated by Django 6.0.6 on 2026-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='jamoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('nomi2', models.CharField(max_length=100)),
                ('nomi3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jamoa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('nomi2', models.CharField(max_length=100)),
                ('nomi3', models.CharField(max_length=100)),
            ],
        ),
    ]
