# Generated by Django 6.0.6 on 2026-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_jamoa_jamoa2'),
    ]

    operations = [
        migrations.CreateModel(
            name='dehqon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text2', models.TextField()),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
    ]
