# Generated by Django 6.0.6 on 2026-09-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_dehqon'),
    ]

    operations = [
        migrations.AddField(
            model_name='camment',
            name='image_en',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='camment',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='camment',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='camment',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='sana_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='sana_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='sana_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='camment',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='text2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='text2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='text2_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dehqon',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='email_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='email_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='email_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='ism_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='ism_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='ism_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='mavzu_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='mavzu_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='mavzu_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='izoh',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jamoa2',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantak',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantak',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantak',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantak',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kantak',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kantak',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Email_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Email_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Email_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Phone_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Phone_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Phone_uz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Username_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Username_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='Username_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='massage_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='massage_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kantakt2',
            name='massage_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='march',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_en',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='sana_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sana_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sana_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='narx_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='narx_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='narx_uz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post2',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='nomi2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='nomi2_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='nomi2_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop1',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='image_en',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story14',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story14',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story14',
            name='narx_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='narx_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='narx_uz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='xarid_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='xarid_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story14',
            name='xarid_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='nomi2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='nomi2_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='nomi2_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story15',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='image_en',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story16',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story16',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story16',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story16',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='nomi2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='nomi2_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='nomi2_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story17',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='nomi2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='nomi2_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='nomi2_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story18',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story19',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story19',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story19',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story19',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story19',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story19',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='narx_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='narx_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='narx_uz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story2',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='adres2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='adres2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='adres2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='adres_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='adres_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='adres_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='email_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='email_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='email_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='tel2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='tel2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='tel2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='tel_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='tel_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story20',
            name='tel_uz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='story21',
            name='image_en',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story21',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story21',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='story21',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story21',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story21',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='emailid_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='emailid_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='emailid_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi2_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi2_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story22',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story3',
            name='nomi_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story3',
            name='nomi_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story3',
            name='nomi_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story3',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story3',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story3',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story4',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story4',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story4',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story4',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story4',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story4',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story5',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story5',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story5',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story5',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story5',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story5',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story6',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story6',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story6',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story6',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story6',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story6',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story7',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story7',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story7',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story7',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story7',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story7',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story8',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story8',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story8',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story8',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story8',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story8',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story9',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story9',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story9',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='narx_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='narx_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='narx_uz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi4_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi4_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi4_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='nomi2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='nomi2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='nomi2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='nomi_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='nomi_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='nomi_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xarid2',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xarid3',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid3',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xarid3',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
